author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Number-Tolerant
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.0
version: 1.550
